### PR TITLE
Added instruction to install fish on NixOS

### PR DESCRIPTION
**Pull request by mehandes**
Tried to keep the aspect ration for the lower row of icons, not sure if the added icon is not too big. Waiting for feedback

### CODE REVIEW

**Comment by floam** [comment]
I believe the way you are linking to the asset on GitHub with the blob hash means it will forever only link to a specific revision. Might `https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/fish/default.nix` be better? (I could be confused.)

**Comment by mehandes** [comment]
@floam of course you're right! Will fix it soon

**Comment by mehandes** [comment]
@floam I would like to tweak the logo size also, may I add some CSS for that, or it would be better if I had tweaked it in some graphical software?

**Comment by floam** [comment]
Assuming you have access to a high resolution/scalable original, it is going to look best if you use Photoshop or whatever tool to size the image to the exact size you want so that browsers do not scale it. (If you're feeling cool, provide the image at 2x the desired width and height and just use `width="x" height="y"` on the image tag with the final rendered size so that on high resolution "retina" displays there's a bit of extra clarity.)

**Comment by ridiculousfish** [comment]
Should be fine to set the size of the image in the `img` tag. I'll pngcrush or whatever the image to make it smaller.

**Comment by mehandes** [comment]
@floam @ridiculousfish I did some PNG optimizations, forgot ofc about imgrc, srcset, <picture/> etc. By tweaking I meant adding some border either in the image alone or in the CSS to 'contain' that image more in the center (cause now it looks much overgrown compared to others).

obraz

**Comment by floam** [comment]
If it doesn't offend the Nix people, that image might fit in better with the logo centered above and the text below. Otherwise I'd probably just add some transparent margin to the PNG to make it fit better rather than tweak it in CSS for the sake of keeping this contained.

**Comment by ridiculousfish** [comment]
Yeah that does look out of place. I also agree with floam's observation that it would look more consistent if it were oriented vertically instead of horizontally.

**Comment by mehandes** [comment]
@floam @ridiculousfish Thanks to work of @wmertens, I added the square version of the logo.

**Comment by floam** [comment]
Since that guy made a SVG we could probably just use that, it's well supported these days.

**Comment by mehandes** [comment]
@floam changed

**Comment by mehandes** [comment]
@floam ready to merge (?)

**Comment by ridiculousfish** [comment]
Updated the site

**Pull request merged**
