### PR TITLE
Issue475 fixed

### PR DESCRIPTION
**Pull request by sabinem**
fixes [issue 475](https://github.com/fish-shell/fish-shell/issues/4986)

added 2 sections to the index.html:
- running fish
- switching to fish

These sections were copied from the corresponding sections of the [README.md file of fish-shell repo](https://github.com/fish-shell/fish-shell)

### CODE REVIEW

**Comment by ridiculousfish** [comment]
Thanks for doing this! However I don't think we want this so prominently placed on the main site. The docs need some editing / prioritization, but how about adding it to the top of the tutorial (in `_site/tutorial.html`)?

**Comment by zanchey** [comment]
Doesn't the tutorial come from the main repository's `doc_src/tutorial.hdr` file?

**Comment by sabinem** [comment]
@zanchey: yes I think you are right, it is coming from there and I will attempt to add it there then. I will work on that tomorrow.

**Comment by sabinem** [comment]
Any recommendations how to work on this? I read the contributors guidelines in both repos, but I am still unsure how to proceed, since the changes have to be made in `fish-shell` and what has been accomplished will only be visible in `fish-site`. I can see how to make my changes, but then what? How do I make sure that they turn out as expected? Can you point me to some passage in the contribution guide, that I missed in that regard?

**Comment by ridiculousfish** [comment]
Yeah, sorry, I brain-farted. Go ahead and PR against fish-shell, after merging I'll sync to fish-site.

**Comment by zanchey** [comment]
I usually make my changes, then run `make`, then inspect the files in `user_doc`.

**Comment by sabinem** [comment]
Sorry, I am still confused:
after making my changes in `fish-shell/doc_src/` I do what exactly? I am working on a mac
- when I say `make`: I get `make: *** No targets specified and no makefile found.  Stop.`

**Comment by zanchey** [comment]
Sorry, I should have been more clear.

You'll need to follow the directions in [Building from source in the README](https://github.com/fish-shell/fish-shell/blob/master/README.md#building-from-source-all-platforms), but the basics are:

* Make sure you have CMake and Doxygen installed
* Run `mkdir build; cd build`
* Run `cmake .. ; and make`
* Skip the `make install` step
* Inspect the contents of the `build/user_doc/html/tutorial.html` file

Hope that helps - let us know if you need more information.

**Comment by sabinem** [comment]
@zanchey: Thanks a lot for the detailed steps, that helped a lot!

Now that I changed the tutorial and opened a [pull request on fish-shell](https://github.com/fish-shell/fish-shell/pull/5025):
Should I just drop this pull request or do you want me to add anything to the index page as well?

**Comment by ridiculousfish** [comment]
The fish-shell PR has been merged, closing this. Thanks!

**Pull request closed without merging**
