### PR TITLE
Remove Comic Sans

### PR DESCRIPTION
**Pull request by krobelus**
I think this font is quite hard to read and makes the project look
like a joke; fish is fun but not a joke. The tongue-in-cheek mood
works well for people who are already fans of fish but I think the
website should focus on how it is perceived by outsiders.

(Related discussion in #127)

### CODE REVIEW

**Comment by faho** [comment]
I would like to keep this.

To be honest I would also have liked to keep the pink site, so it appears my appetite for jokes is a bit higher.

**Comment by krobelus** [comment]
Possible ways to make such decisions are:

- do not make controversial changes
- or have the component owner (e.g. you) decide

> I would also have liked to keep the pink site

My bad for not asking, I had assumed the readability concerns had priority.
Again, this needs a way to make decisions. Those reverts can be a lot of work so I'd prefer deciding first.

**Comment by zanchey** [comment]
I find it pretty difficult to read as well, so I think it might have run its course.

**Comment by faho** [comment]
Okay, it appears I am the only voice of unreason. Go ahead.

(but this does strengthen my resolve to make an extremely cursed april fools' (but not first of april) version)

**Pull request closed without merging**
