### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by faho**
The colors are roughly the same as in
https://github.com/fish-shell/fish-shell/pull/8043 (as in I picked the colors where applicable and added new colors where I needed them).

One fly in the ointment is that the distro logos don't look good on a
dark background, so we add a cheesy white background to them.

# Screenshot:

Screenshot 2021-06-06 at 10-35-52 fish shell

And here's what the distro logos would look like without the background:

Screenshot_20210606_103645

This might be solvable with higher resolution logos (some are kinda small) or maybe it requires special "dark mode" versions of them. But since Fedora requires you to send them an email begging for the logo and Ubuntu apparently no longer has a stacked version (with logo and text in roughly square shape) I'm not keen on it.

### CODE REVIEW

**Comment by faho** [comment]
Live version at https://bean.solutions/fish-site/.

**Comment by faho** [comment]
Okay, I marked the logos that don't work on a dark background specifically. This applies to Ubuntu, Debian, Fedora, Suse, CentOS (is that still a thing we support?), Arch, Gentoo.

I've tried to find new logos, openSUSE, Debian and Gentoo have some available that work okay-ish. Like I said, Fedora's policy is awkward and Ubuntu doesn't have a working shape. We would also need to change the layout so the size isn't inconsistent when the logos aren't the same aspect ratio (easy enough to do with flexbox). But that's work for later.

**Comment by zanchey** [comment]
> CentOS (is that still a thing we support?)

Yes (we currently build for CentOS 7 and 8, as RHEL 8 is not available on OBS, and the CentOS 7 packages are binary compatible with RHEL 7).

**Comment by faho** [comment]
Given that CentOS has... changed, recently, with the entire "CentOS Stream" thing, will that stay binary compatible? Can we keep building packages that work on RHEL?

Or, to bring it back to the question at hand: Is it worth investing time to look for a nicer CentOS logo that works on both backgrounds?

**Comment by zanchey** [comment]
Good questions, I don't know. In regard to a logo, it looks like there's some versions at https://wiki.centos.org/ArtWork/Brand/Logo which might be helpful (the dark version has a white outline to make it stand out).

**Comment by faho** [comment]
>the dark version has a white outline to make it stand out

Separate dark versions aren't *ideal*, because we'd have to make the user download both. One image that works on both backgrounds would be preferable. But given that it's a 12kb svg and we might even render it to a png of ~3k, that's probably overthinking it.

**Comment by faho** [comment]
Jaysus, these logos are killing me.

Just getting logos

1. In vaguely the right aspect ratio
2. That work on a dark background

is basically impossible.

The aspect issue would probably be solved if we flexboxed this (so all the items gain the same height), but the background?

**Comment by faho** [comment]
Alright, I've switched to a flexbox layout, switched some of the logos, and added rounded corners to the ones we add a white background to (which made a lot more difference than I would have guessed!).

This is now what it looks like:

Screenshot 2021-06-06 at 22-13-03 fish shell

**Comment by zanchey** [comment]
That looks great! CSS has improved a lot.

**Comment by faho** [comment]
Merged and deployed!

**Comment by zanchey** [comment]
I really like the rounded corners on the Linux distributions, but it doesn't look like they're on the MacPorts or WSL logos in Chrome 91?

**Comment by faho** [comment]
>I really like the rounded corners on the Linux distributions, but it doesn't look like they're on the MacPorts or WSL logos in Chrome 91?

Never added them there because they have the white background in the image.

Let's just add them.

**Pull request merged**
