### PR TITLE
Update installation instruction for Linux distros

### PR DESCRIPTION
**Pull request by luc14n0**
A simple update of links and addition of installation instructions for Debian, Ubuntu, and openSUSE Leap and Tumbleweed.

---

image

### CODE REVIEW

**Comment by faho** [comment]
The instructions are listed on the OBS site.

We don't want to give package manager instructions for these because they just lead to people installing the outdated repo packages.

Sorry!

**Comment by luc14n0** [comment]
No worries, I see your point.

If newer versions of the software doesn't raise version requirements of its dependencies, or if it does in a very conservative fashion, it's always possible for distributors to upgrade their Fish version release. But this is not the place for such discussion.

Thanks for your time.

**Comment by faho** [comment]
>it's always possible for distributors to upgrade their Fish version release

It is not that it isn't *possible*. It is easy to build fish. You can build a really new fish on quite an old distribution (basically you need a C++11-capable compiler and you're good).

It is that these distributions are "stable", in the sense that they *do* *not* *change* - so they won't upgrade from, for example, fish 3.5.x to 3.6.x, as a matter of policy.

(and as a matter of practicality, fish is in Ubuntu's "universe" repo, which means it is essentially unmaintained - so they won't even upgrade from 3.6.0 to 3.6.1)

**Comment by luc14n0** [comment]
Yeah, I'm aware of how regular distributions maintain software. Some are more flexible than others, boiling down to whether the package has an active dedicated maintainer. It is what it is.

**Pull request closed without merging**
