### PR TITLE
Add FreeBSD installation instructions to "Go fish"

### PR DESCRIPTION
**Pull request by AnotherKamila**
This change is [Reviewable](https://reviewable.io/reviews/fish-shell/fish-site/69)

### CODE REVIEW

**Comment by AnotherKamila** [comment]
Oops, um, see #68 :-D Perhaps never mind :-D

**Comment by lwhsu** [comment]
Yeah, this version is more complete as there is OS detection. I am somehow not sure the tab should be "BSD" or "FreeBSD", as I guess other BSDs might be interested in adding their information.  Any thoughts?

**Comment by AnotherKamila** [comment]
@lwhsu other BSDs are a good point. I have changed this accordingly. Thanks!

**Comment by lwhsu** [comment]
@zanchey do you think we can have this merged?

**Comment by ridiculousfish** [comment]
Merged and deployed, thanks!!

**Pull request merged**
