### PR TITLE
Add more links to “Contact Us”

### PR DESCRIPTION
**Pull request by KrzysiekJ**

### CODE REVIEW

**Comment by ridiculousfish** [comment]
Nice. Is the IRC still active?

**Comment by zanchey** [comment]
There's still a few people in it, but Gitter is probably a lot more responsive - plus it's searchable.

**Comment by KrzysiekJ** [comment]
It seems there is some volume on IRC. This pull request actually comes from the fact that I had been searching for the IRC channel.

**Comment by ridiculousfish** [comment]
Merged, thanks! I want to reorder the places a bit and then I'll upload to the site.

**Comment by ridiculousfish** [comment]
Uploaded with some additional changes

**Pull request merged**
