### PR TITLE
:boom: Site modernization w/ bootstrap 3.3.5

### PR DESCRIPTION
**Pull request by Acidhub**
- Added bootstrap v3.3.5 (via CDN)
- Pure HTML5/CSS3
- Responsive design (hope works in any device/resolution)
- Thumbs now show collapseds screenshots
- Added bootstrap.js components like popovers
- Redesign of distros/systems tabs

In PC/Mac browsers site is almost unchanged in surface (I tried to keep all original feel).
Hope you like. :smiley: 
And here a sample in mobile browser:

screenshot_2015-07-19-00-47-01
screenshot_2015-07-19-00-48-09

### CODE REVIEW

**Comment by zanchey** [comment]
Impressive!

There were a couple of people (or maybe one person and a sockpuppet) on HN complaining about the [need for JavaScript](https://news.ycombinator.com/item?id=9567361), which did make me roll my eyes a bit - the current site falls back perfectly in textmode browsers! - but certainly is something we should consider in adding any extra JS. The proposed design certainly doesn't hide any information like the current design.

I wonder if a lightbox-style transition would work better for the screenshots than the slider.

**Comment by ridiculousfish** [comment]
Wow, this was a ton of work! Helvetica Neue sure looks nice.

I put it up at [http://fishshell.com/staging/](http://fishshell.com/staging/). Here's some problems I noticed:

- On desktop, the screenshots may be revealed below the fold. See this screenshot: The autosuggestion screenshot is actually revealed but offscreen. 
screen shot 2015-07-23 at 11 13 16 am

- On my iPhone, revealing a screenshot causes the whole page to reflow to fill half the screen (and it's cut off the bottom again):

img_6380

- On my default window size, it shows up in single column mode, where the spacing is quite wonky:
screen shot 2015-07-23 at 11 15 36 am

- Some sections are centered ("Teach me to fish"), and others are left aligned ("Go fish")

**Comment by ridiculousfish** [comment]
The site uses JavaScript to switch among the tabs for the different release types (OS X, Linux, Windows, tarball) and to select the initial tab based on guessing the user's OS. [mosh](https://mosh.mit.edu) chooses to just put them all in the same page. Maybe that's OK.

**Comment by Acidhub** [comment]
I will work on improvements.
The suggestion "lightbox-style" from @zanchey will work well to solve the problems pointed out by @ridiculousfish, so I kill two birds with one stone.
And the implementation of detecting the current system for default tab will also be implemented, since we are loading the jQuery.

I'm open to suggestions.

**Comment by ridiculousfish** [comment]
Thanks @acidhub. Now I don't remember why it uses jquery - is that necessary for bootstrap?

**Comment by Acidhub** [comment]
Yes, bootstrap uses jquery for various things like modal, popover, tabs, tooltips, transitions and so on

**Comment by Acidhub** [comment]
Adjustments made, please test it out :+1:

**Comment by ridiculousfish** [comment]
Updated at [http://fishshell.com/staging/](http://fishshell.com/staging/). Here's things I notice now:

The spacing still seems very inconsistent. Compare the tight margins on the left sides with the enormous margins on the hero content at the top:

screen shot 2015-07-23 at 8 46 18 pm

The tabs aren't connecting to their associated content:

screen shot 2015-07-23 at 8 47 20 pm

The "No Installation" button is very prominent, dominating the download link itself:
screen shot 2015-07-23 at 8 48 18 pm

There's an big void (empty space) here:

screen shot 2015-07-23 at 8 49 20 pm

and here:

screen shot 2015-07-23 at 8 54 31 pm

This is the challenge of horizontally-resizing websites, and why the current design is fixed width. I'm all for making it a responsive site, but not at the cost of these types of visual regressions.

I wonder if it's possible to design it with some set fixed sizes, and have it select between those.

**Pull request closed without merging**
