### PR TITLE
Added instruction to install fish on FreeBSD

### PR DESCRIPTION
**Pull request by lwhsu**

### CODE REVIEW

**Comment by zanchey** [comment]
I've always been a bit wary about adding FreeBSD here, because we don't provide up-to-date packages and the package you get with `pkg install` can potentially be very old.

**Comment by AnotherKamila** [comment]
FreeBSD tends to be very good at keeping packages up to date. Therefore I believe this is not a good reason to exclude it. I totally understand the reasoning, as packages in some Linux distros are notoriously terribly old, but this really isn't a problem with FreeBSD.

If you are still worried (which you should not be, because FreeBSD is good at this), let me know, I'm sure we can figure something out.

**Comment by lwhsu** [comment]
I believe that nowadays `pkg install fish` can give you the latest package (well, it's 2.7.0 now because 2.7.1 seems doesn't include fixes for FreeBSD, but updating to 2.7.1 is very straightforward.)  The current maintainer of shells/fish is an active FreeBSD developer so fish on FreeBSD always receives fast updates and fixes, even on the developing version of FreeBSD.

**Comment by lwhsu** [comment]
Close this since #69 is much better.

**Pull request closed without merging**
