### PR TITLE
My changes

### PR DESCRIPTION
**Pull request by egorsmkv**

### CODE REVIEW

**Comment by egorsmkv** [comment]
@ridiculousfish ping

**Comment by ridiculousfish** [comment]
Thanks for doing this! What am I looking at here? What's the goal of this change set?

**Comment by egorsmkv** [comment]
In general - is to improve the layout.

* To make an adjustment of HTML-files so that they are valid.
* Imposition of styles in the CSS-file from code.

The next change I want to update the Bootstrap to the latest version. By the way, all the changes will not alter the external appearance design.

**Comment by ridiculousfish** [comment]
Finished reviewing - some very nice changes here. Thanks for doing this!

Two quibbles:

1. Please undo the change to use "protocol-relative URLs" for the CDN files. [It's now considered best to just always use https](http://www.paulirish.com/2010/the-protocol-relative-url/). Protocol-relative URLs also break viewing the page with the file:// protocol.
2. The initial tab highlight is not present. The tab looks like this:
screen shot 2016-06-02 at 1 41 51 pm

should look like this:

screen shot 2016-06-02 at 1 41 45 pm

Fix those and I'll merge. Thanks again!

**Comment by egorsmkv** [comment]
@ridiculousfish, done. Please, check updates.

**Comment by ridiculousfish** [comment]
Merged. Thank you!!

**Comment by egorsmkv** [comment]
@ridiculousfish you can add the information for version 2.3.0?

**Comment by ridiculousfish** [comment]
Yes, to my shame I haven't merged those changes yet.

**Comment by egorsmkv** [comment]
ok, I'll wait

**Pull request merged**
